name: Email Alert on Pull

on:
  pull_request:
    types: [opened, closed]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email alert
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: sandbox.smtp.mailtrap.io
          server_port: 465
          username: $6b2d8e13764f87
          password: $ba0a9d54c31a6e
          subject: "GitHub Pull Request Alert"
          body: "A pull request has been created or merged in the repository."
          to: kh.lytheng@gmail.com
          from: noreply@example.com
